# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nest_pb2 as nest__pb2


class NestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recognize = channel.stream_stream(
                '/com.nbp.cdncp.nest.grpc.proto.v1.NestService/recognize',
                request_serializer=nest__pb2.NestRequest.SerializeToString,
                response_deserializer=nest__pb2.NestResponse.FromString,
                )


class NestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def recognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recognize': grpc.stream_stream_rpc_method_handler(
                    servicer.recognize,
                    request_deserializer=nest__pb2.NestRequest.FromString,
                    response_serializer=nest__pb2.NestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.nbp.cdncp.nest.grpc.proto.v1.NestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/com.nbp.cdncp.nest.grpc.proto.v1.NestService/recognize',
            nest__pb2.NestRequest.SerializeToString,
            nest__pb2.NestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
